name: CI

on: push

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    uses: ./.github/workflows/test-biome.yml

  typecheck:
    uses: ./.github/workflows/test-typecheck.yml

  go-test:
    uses: ./.github/workflows/test-go.yml

  go-lint:
    uses: ./.github/workflows/test-go-lint.yml

  go-format:
    uses: ./.github/workflows/test-go-format.yml

  build:
    uses: ./.github/workflows/build.yml
    needs: [biome, typecheck, go-test, go-lint, go-format]
