name: go-lint

on:
  workflow_call:

permissions:
  contents: read

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: packages/engine-wasm/go.mod
          cache-dependency-path: packages/engine-wasm/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: packages/engine-wasm
